### ISSUE TITLE
README files in search results

### ISSUE THREAD

**Issue by richa208** [OpenGenus/quark#10]
**This is a(n):**

- [ ] New feature proposal
- [ ] Reporting a keyword
- [ ] Error
- [ ] Proposal to the Search Engine
- [x] Other

**Details:**

Certain algorithms are having a README.md file also which gets dispayed during searching. But as these files are not containing any algorithmic code they should not be there in the suggestions.
![readme](https://user-images.githubusercontent.com/25206394/36060630-6c862aea-0e73-11e8-9384-43da42eba939.png)

**Comment by richa208** [comment]
I would like to work on this issue if this sounds essential.

**Comment by AdiChat** [comment]
We can remove the `README` files from consideration as they do not contain enough information at the moment. `Readme`s can be useful at the later stage. 

Yes, you may remove them from the results. 👍
