### ISSUE TITLE
Scroll to Top on button click

### ISSUE THREAD

**Issue by dimi-23** [OpenGenus/quark#110]
**This is a(n):**

- [x] New feature proposal
- [ ] Reporting a keyword
- [ ] Error
- [ ] Proposal to the Search Engine
- [ ] Other

**Details:** Add a floating button to enable the user to scroll to top.

**Expected Behavior**: When reaching at the bottom of the page, a floating button should pop up to enable the user to go to the top on the click of a button.

**Actual Behavior**: After scrolling till bottom of the page, the user needs to manually scroll up.

**Would you like to work on this issue?**

- [x] Yes
- [ ] No

**Comment by dimi-23** [comment]
@AdiChat kindly tell if the issue if significant to be worked on, I would like to work on it.

**Comment by AdiChat** [comment]
Search results will increase as we go on to tap into different resources. Also, at present, a lot of results are returned for general search terms. This will be a nice addition. Go for it. :+1:
