### ISSUE TITLE
Dynamically Refresh Bookmarks

### ISSUE THREAD

**Issue by AnkitaKhurana** [OpenGenus/quark#111]
**This is a(n):**

- [ ] New feature proposal
- [ ] Reporting a keyword
- [ ] Error
- [ ] Proposal to the Search Engine
- [x] Other

**Details:**
The stars in the favorites list when used to delete a code area requires recalling of favorites area to see the change.
The area should be updated as soon as any favorite is added or deleted in the list.

**Expected Behavior**:
On clicking Favorited code star the area should show the new updated list immediately.

**Actual Behavior**:
![star](https://user-images.githubusercontent.com/13145896/37415437-6b9a6746-27d1-11e8-85db-e93d5da43f0a.gif)

**Screenshots (if any)**: N/A

**Would you like to work on this issue?**

- [x] Yes
- [ ] No

**Comment by AdiChat** [comment]
Sounds good. Go for it :+1:
