### ISSUE TITLE
Public communication channel

### ISSUE THREAD

**Issue by jainaman224** [OpenGenus/quark#13]
**This is a(n):**
- [ ] New feature proposal
- [ ] Reporting a keyword
- [ ] Error
- [ ] Proposal to the Search Engine
- [x] Other

**Details:**
There is a need for communication channel as quark is participating in RGSoC this year. Contributors needs platform to give suggestion and ask queries.

**Comment by AdiChat** [comment]
OpenGenus has a public discussion platform ([see this](https://discourse.opengenus.org)) in addition to our Slack workspace.
