### ISSUE TITLE
Adding a 'Bookmark' feature

### ISSUE THREAD

**Issue by dimi-23** [OpenGenus/quark#14]
**This is a(n):**

- [x] New feature proposal
- [ ] Reporting a keyword
- [ ] Error
- [ ] Proposal to the Search Engine
- [ ] Other

**Details:**

There is no 'bookmark' feature in the current UI. There is a need for a star icon on each code so that when the user clicks on it, it is saved to his favorites which appear on the front page when the extension is opened.

**Comment by dimi-23** [comment]
I would like to work on this issue.

**Comment by AdiChat** [comment]
Yes, a bookmarking feature will, greatly, enhance the learning experience. Go for it 👍
