### ISSUE TITLE
improper loading of logo and buttons when run quark locally

### ISSUE THREAD

**Issue by iamrajiv** [OpenGenus/quark#156]
**This is a(n):**

- [x] Error

**Details:**

When running Quark locally in my system by opening `popup.html` it loads differently as compared to live Quark chrome extension. In local Quark i.e. after cloning the code and running in system locally, the logo does not load and there is `Go` button in local Quark but it is not there in live chrome extension of Quark. 

**Screenshots (if any)**:

![live](https://user-images.githubusercontent.com/42106787/62351167-69cbf300-b522-11e9-9a1f-9d25fbc99de4.JPG)
 **Running Live Quark in chrome extension**

![local](https://user-images.githubusercontent.com/42106787/62351234-93851a00-b522-11e9-9a34-a98ed76a74e6.JPG)
 **Running Quark Locally in System**

**Would you like to work on this issue?**

- [x] Yes
- [ ] No

**Comment by CaptainLazarus** [comment]
I guess this has been fixed because I tried reproducing it and it isn't getting reproduced. I wouldn't actually reccomend running it like that though because the engine doesn't work when used like that.
