### ISSUE TITLE
Unnecessary redirecting to new window 

### ISSUE THREAD

**Issue by pragyach** [OpenGenus/quark#23]
**This is a(n):**

- [ ] New feature proposal
- [ ] Reporting a keyword
- [x] Error
- [ ] Proposal to the Search Engine
- [ ] Other

**Details:**

If user clicks anywhere in the blank right side of the page another tab opens up with the corresponding algorithm in that line even if the user did not meant to open it.
If this error is found suitable I would like to work on it.

**Comment by AnkitaKhurana** [comment]
Hi, 
Thanks for finding this issue the new UI has no such whitespace click problem. :+1: 
Kindly check the updated code.
The issue is good to close.
