### ISSUE TITLE
'Help' option

### ISSUE THREAD

**Issue by dimi-23** [OpenGenus/quark#24]
**This is a(n):**

- [x] New feature proposal
- [ ] Reporting a keyword
- [ ] Error
- [ ] Proposal to the Search Engine
- [ ] Other

**Details:**

There is no ‘Help’ option on the main screen which summarizes the user of the various features and working of the extension. A small ‘Help’ button can be added to the same.

**Comment by dimi-23** [comment]
I would like to work on this issue, if such a feature seems important.

**Comment by AdiChat** [comment]
Yes, a `help` option will guide users in making the full use of Quark. Go for it 👍
