### ISSUE TITLE
Offline apps in Quark

### ISSUE THREAD

**Issue by AnkitaKhurana** [OpenGenus/quark#26]
**This is a(n):**

- [X] New feature proposal
- [ ] Reporting a keyword
- [ ] Error
- [ ] Proposal to the Search Engine
- [ ] Other

**Details:**

Create a framework for integrating offline apps such as a calculator, a stopwatch, timezone converter and many others with the search results.

**Comment by AnkitaKhurana** [comment]
![image](https://user-images.githubusercontent.com/13145896/36328477-4474e978-1388-11e8-89b9-2dc363863f0a.png)

@AdiChat 
The first app calculator , Kindly give suggestions on the same.

**Comment by AdiChat** [comment]
The design is perfect. 😍
