### ISSUE TITLE
Wrong positioning of elements

### ISSUE THREAD

**Issue by richa208** [OpenGenus/quark#27]
**This is a(n):**

- [ ] New feature proposal
- [ ] Reporting a keyword
- [x] Error
- [ ] Proposal to the Search Engine
- [ ] Other

**Details:**

When we type just blank spaces in the search bar, then the alignment of image and corresponding suggestions are not in the way they should be.
![screenshot from 2018-02-17 10-37-14](https://user-images.githubusercontent.com/25206394/36338220-478e2dee-13cf-11e8-95ac-0c27cc1645e6.png)

**Comment by richa208** [comment]
I would like to correct this.

**Comment by AdiChat** [comment]
Yes, go for it 👍
