### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by richa208** [OpenGenus/quark#28]
**This is a(n):**

- [ ] New feature proposal
- [ ] Reporting a keyword
- [ ] Error
- [ ] Proposal to the Search Engine
- [x] Other

**Details:**

Documenting CONTRIBUTING.md with contributing guidelines that would help newcomers.

**Comment by richa208** [comment]
I would like to work on this if this seems essential.

**Comment by AdiChat** [comment]
Yes, documentation is important. Go for it 👍
