### ISSUE TITLE
Feedback Suggestion

### ISSUE THREAD

**Issue by richa208** [OpenGenus/quark#29]
**This is a(n):**

- [x] New feature proposal
- [ ] Reporting a keyword
- [ ] Error
- [ ] Proposal to the Search Engine
- [ ] Other

**Details:**

A feedback option can be provided by which users can give feedback to quark.
This option would work only when we are online like the other links to github repositories.

**Comment by richa208** [comment]
I would like to work on this if this seems essential.

**Comment by AdiChat** [comment]
Yes, an option to submit feedback will be nice. You can use our [Discourse forum](http://discourse.opengenus.org/) for this purpose. Go for it 👍
