### ISSUE TITLE
Quick search option

### ISSUE THREAD

**Issue by richa208** [OpenGenus/quark#30]
**This is a(n):**

- [x] New feature proposal
- [ ] Reporting a keyword
- [ ] Error
- [ ] Proposal to the Search Engine
- [ ] Other

**Details:**

A quick search option can be made by directly clicking on the extension icon ie. if user uses that option by clicking on the icon, he can type any query there and then he will be redirected directly to the corresponding page of related algorithms.

**Comment by richa208** [comment]
I would like to work on this if this seems important.

**Comment by AdiChat** [comment]
Currently, on clicking the extension icon, the user is directed to the search engine page where users can make any particular search. If this is implemented, the direct access to the homepage may be hindered. 

Instead, you may work on implementing a feature whereby right-clicking a highlighted word on any webpage, an option like `Search in Quark` may appear.

**Comment by richa208** [comment]
Can you please suggest some idea through which I could redirect the user from an online page to an offline extension because I am having some doubts like for this purpose user needs to be online and also as Quark is an offline extension how would we redirect him here.
Kindly give your suggestions.
