### ISSUE TITLE
Display Results of Offline Search in Alphabetical Order

### ISSUE THREAD

**Issue by Aditi574** [OpenGenus/quark#40]
**This is a(n):**

- [ ] New feature proposal
- [ ] Reporting a keyword
- [ ] Error
- [ ] Proposal to the Search Engine
- [x] Other

**Details:**

As of now the results of an offline search are visible on the screen in a random order (image attached). A better idea will be to sort these results alphabetically so that it becomes easier for the user to scroll to the desired topic directly rather than by going through all other topics.
![im1](https://user-images.githubusercontent.com/19898120/36445759-3738b6fc-16a5-11e8-95af-2fe3c9a42a1e.PNG)

**Comment by Aditi574** [comment]
@AdiChat should I start working on this?

**Comment by AdiChat** [comment]
Yes, getting results in a sorted order will help in an ordered learning experience and remove the current uncertainty. You may work on this. :+1:
