### ISSUE TITLE
Filtered search results are not shown

### ISSUE THREAD

**Issue by richa208** [OpenGenus/quark#5]
**This is a(n):**

- [x] New feature proposal
- [ ] Reporting a keyword
- [ ] Error
- [ ] Proposal to the Search Engine
- [ ] Other

**Details:**

On searching for any particular algorithm like bubble sort the results should include only algorithms of available bubble sort but it contains all the available sorting algorithms.

**Comment by richa208** [comment]
I would like to work on this if this issue sounds essential.

**Comment by AdiChat** [comment]
Yes, getting focused search results is important. Go for it 👍
