### ISSUE TITLE
Organised Favourites 

### ISSUE THREAD

**Issue by AnkitaKhurana** [OpenGenus/quark#64]
**This is a(n):**

- [x] New feature proposal
- [ ] Reporting a keyword
- [ ] Error
- [ ] Proposal to the Search Engine
- [ ] Other

**Details:**

The favorites display area can be enhanced for easy searching and sorting of favorites to make it more systematic - 
- Sorting them according to date/time added
- Code Language 
- Area(topic) they belong to

**Comment by AnkitaKhurana** [comment]
I would like to work on this enhancement for the extension.

**Comment by AdiChat** [comment]
Sure. Go for it :+1:
