### ISSUE TITLE
Clearance option

### ISSUE THREAD

**Issue by richa208** [OpenGenus/quark#66]
**This is a(n):**

- [x] New feature proposal
- [ ] Reporting a keyword
- [ ] Error
- [ ] Proposal to the Search Engine
- [ ] Other

**Details:**

A clearance option in the form of 'cross button' in the text box so that the user does not need to use backspace every time to type another query.

**Comment by richa208** [comment]
I would like to do this if this seems essential.

**Comment by AdiChat** [comment]
Sure. Go for it. :+1:
