### ISSUE TITLE
Showing total no. of search results 

### ISSUE THREAD

**Issue by richa208** [OpenGenus/quark#7]
**This is a(n):**

- [x] New feature proposal
- [ ] Reporting a keyword
- [ ] Error
- [ ] Proposal to the Search Engine
- [ ] Other

**Details:**
The total number of matching results found on searching for any algorithm could be displayed.

**Comment by richa208** [comment]
I would like to work on this..

**Comment by AdiChat** [comment]
Yes, showing the total number of search results will be nice. Go for it 👍
