### ISSUE TITLE
Updating ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by richa208** [OpenGenus/quark#74]
**This is a(n):**

- [ ] New feature proposal
- [ ] Reporting a keyword
- [ ] Error
- [ ] Proposal to the Search Engine
- [x] Other

**Details:**

We can add more details while creating a new issue like what is the current behaviour due to this issue and what it should be actually or a checkbox if user wants to work on this issue and other similar options that would make the issue more clear.

**Comment by richa208** [comment]
I would like to make this update if it is required.

**Comment by AdiChat** [comment]
Sure. Go for it :+1:
