### ISSUE TITLE
Error in Favourite feature

### ISSUE THREAD

**Issue by monikasingh20** [OpenGenus/quark#88]
**This is a(n):**

- [ ] New feature proposal
- [ ] Reporting a keyword
- [Error in Favourite feature.] Error
- [ ] Proposal to the Search Engine
- [ ] Other

Description:

After selecting favourite option for any code , and then clicking on the same file , it's not showing the required code in browser.
@AdiChat please review this error, suggest if it is a valid error or not.

![screenshot from 2018-03-07 15-10-38](https://user-images.githubusercontent.com/29702439/37084926-c48a0e28-2219-11e8-96fb-d0105e435b54.png)

Would you like to work on this issue?
    yes.I would like to work on this issue.

**Comment by monikasingh20** [comment]
@AdiChat please review this error, and suggest can we work on this issue.

**Comment by richa208** [comment]
Hi @monikasingh20 
It is working fine for me and there is no such error coming.
I guess you can look up  [here](https://windowsreport.com/type-of-file-can-harm-computer/) for help. :+1:
