### ISSUE TITLE
Footer changes made in merged Pull Request needs Correction 

### ISSUE THREAD

**Issue by AnkitaKhurana** [OpenGenus/quark#92]
**This is a(n):**

- [ ] New feature proposal
- [ ] Reporting a keyword
- [x] Error
- [ ] Proposal to the Search Engine
- [ ] Other

**Details:**

This footer fix in https://github.com/OpenGenus/quark/pull/62 is not working properly in this merge. I have uploaded a Demo file to show the errors.
Issues : 
- The last row results are hidden in many search queries
- The expanded Results also hide in many cases 

The footer CSS was made  `position: relative` in https://github.com/OpenGenus/quark/pull/20 to correct the same issue which was corrected there. 
The main issue with footer right now is 
- The width is different than the expected body width it is taking 
- When the page is showing fewer queries results/Error page the footer floats a little. 

@AdiChat kindly look into this. 
As showing all results correctly is a higher priority. 

**Expected Behavior**: Correct sized footer and all query items displayed

**Actual Behavior**: Already mentioned above 

**Screenshots (if any)**:
![footer](https://user-images.githubusercontent.com/13145896/37138061-9ebcb23a-22ce-11e8-8238-eaf1fe8a51f1.gif)

**Would you like to work on this issue?**

- [x] Yes
- [ ] No

**Comment by AdiChat** [comment]
Yes, this needs to be resolved. :+1:
